# Generated by Django 5.2 on 2025-05-22 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_promptvote_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='author',
            new_name='user',
        ),
        migrations.AddField(
            model_name='prompt',
            name='copied_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='api.prompt'),
        ),
    ]
