# Generated by Django 5.2 on 2025-05-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='downvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prompt',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
