# Generated by Django 5.2 on 2025-05-15 12:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_promptvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promptvote',
            options={'verbose_name': 'Prompt Vote', 'verbose_name_plural': 'Prompt Votes'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='promptvote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the vote was last updated'),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='author',
            field=models.ForeignKey(help_text='The user who created this prompt', on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the prompt was created'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='downvotes',
            field=models.PositiveIntegerField(default=0, help_text='Total number of downvotes'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether the prompt is publicly visible'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt_text',
            field=models.TextField(help_text='The actual prompt content'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags associated with this prompt', related_name='prompts', to='api.tag'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='title',
            field=models.CharField(help_text='Title of the prompt', max_length=200),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the prompt was last updated'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='upvotes',
            field=models.PositiveIntegerField(default=0, help_text='Total number of upvotes'),
        ),
        migrations.AlterField(
            model_name='promptvote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the vote was cast'),
        ),
        migrations.AlterField(
            model_name='promptvote',
            name='prompt',
            field=models.ForeignKey(help_text='Prompt being voted on', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.prompt'),
        ),
        migrations.AlterField(
            model_name='promptvote',
            name='user',
            field=models.ForeignKey(help_text='User who cast the vote', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='promptvote',
            name='vote_type',
            field=models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], help_text='Type of vote (up/down)', max_length=4),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['-created_at'], name='api_prompt_created_8a8f19_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['-upvotes'], name='api_prompt_upvotes_fe63c2_idx'),
        ),
        migrations.AddIndex(
            model_name='promptvote',
            index=models.Index(fields=['user', 'prompt'], name='api_promptv_user_id_159466_idx'),
        ),
        migrations.AddIndex(
            model_name='promptvote',
            index=models.Index(fields=['vote_type'], name='api_promptv_vote_ty_14ed0d_idx'),
        ),
        migrations.AddIndex(
            model_name='promptvote',
            index=models.Index(fields=['-created_at'], name='api_promptv_created_0bc065_idx'),
        ),
    ]
