# Generated by Django 5.2 on 2025-05-15 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_promptvote_options_alter_tag_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promptvote',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='prompt',
            name='api_prompt_created_8a8f19_idx',
        ),
        migrations.RemoveIndex(
            model_name='prompt',
            name='api_prompt_upvotes_fe63c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='promptvote',
            name='api_promptv_user_id_159466_idx',
        ),
        migrations.RemoveIndex(
            model_name='promptvote',
            name='api_promptv_vote_ty_14ed0d_idx',
        ),
        migrations.RemoveIndex(
            model_name='promptvote',
            name='api_promptv_created_0bc065_idx',
        ),
        migrations.RemoveField(
            model_name='promptvote',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='prompt',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='downvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='prompts', to='api.tag'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promptvote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='promptvote',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prompt'),
        ),
        migrations.AlterField(
            model_name='promptvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='promptvote',
            name='vote_type',
            field=models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], max_length=4),
        ),
    ]
