# Generated by Django 5.2 on 2025-05-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_author_prompt_user_prompt_copied_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_predefined',
            field=models.BooleanField(default=False),
        ),
    ]
